# Generated by Django 4.1 on 2022-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NewsUrls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sentences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence_de", models.CharField(max_length=255)),
                ("sentence_jp", models.CharField(max_length=255)),
                ("category_id", models.IntegerField(0)),
                ("url_id", models.IntegerField(0)),
            ],
        ),
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_de", models.CharField(max_length=255)),
                ("word_jp", models.CharField(max_length=255)),
                ("category_id", models.IntegerField(0)),
                ("url_id", models.IntegerField(0)),
            ],
        ),
    ]
