# Generated by Django 4.1 on 2022-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0002_alter_sentences_category_id_alter_sentences_url_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentences",
            name="category_id",
            field=models.IntegerField(null=True, verbose_name=0),
        ),
        migrations.AlterField(
            model_name="sentences",
            name="url_id",
            field=models.IntegerField(null=True, verbose_name=0),
        ),
        migrations.AlterField(
            model_name="words",
            name="category_id",
            field=models.IntegerField(null=True, verbose_name=0),
        ),
        migrations.AlterField(
            model_name="words",
            name="url_id",
            field=models.IntegerField(null=True, verbose_name=0),
        ),
    ]
