# Generated by Django 4.1 on 2022-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0004_alter_sentences_sentence_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("describe", models.CharField(max_length=1000)),
                ("url", models.URLField()),
                ("usrname", models.TextField()),
                ("apikey", models.TextField()),
            ],
        ),
    ]

