# Generated by Django 4.1 on 2022-08-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0005_apis"),
    ]

    operations = [
        migrations.AddField(
            model_name="apis",
            name="form",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
