# Generated by Django 4.1 on 2022-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0006_apis_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="data_NewsApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("descripriotn", models.CharField(max_length=1000)),
                ("url", models.URLField()),
                ("publishedAt", models.DateField()),
                ("content", models.TextField(max_length=10000)),
            ],
        ),
    ]
