# Generated by Django 4.1 on 2022-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0007_data_newsapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="data_newsapi",
            name="api_id",
            field=models.IntegerField(null=True, verbose_name=0),
        ),
    ]
